"""empty message

Revision ID: 50335154ff7e
Revises: bc9ee0f55723
Create Date: 2020-08-31 16:42:58.056747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50335154ff7e'
down_revision = 'bc9ee0f55723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('type', sa.String(), nullable=False))
    op.drop_column('images', 'table')
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'name')
    op.add_column('images', sa.Column('table', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('images', 'type')
    # ### end Alembic commands ###
