"""title no longer required unique for expenses

Revision ID: 7c96587ec602
Revises: 50335154ff7e
Create Date: 2020-10-14 10:48:39.545637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c96587ec602'
down_revision = '50335154ff7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expenses_title_key', 'expenses', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('expenses_title_key', 'expenses', ['title'])
    # ### end Alembic commands ###
