"""empty message

Revision ID: bc9ee0f55723
Revises: e473f4f40a47
Create Date: 2020-08-31 12:45:13.317023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9ee0f55723'
down_revision = 'e473f4f40a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expenses_note_key', 'expenses', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('expenses_note_key', 'expenses', ['note'])
    # ### end Alembic commands ###
